name: yash_sherpura_budventure_task
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  connectivity_plus: ^5.0.1
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.3
  flash: ^3.0.5+2
  injector: ^3.0.0
  provider: ^6.1.1
  dio: ^5.1.2
  retrofit_generator: ^8.0.4
  retrofit: ^4.0.3
  dio_http_cache: ^0.3.0
  json_annotation: ^4.8.1
  pointer_interceptor: ^0.10.1+1
  equatable: ^2.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^3.0.0


dependency_overrides:
  dio: ^5.1.2
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true